### ISSUE TITLE
兄弟，你这个上传的时候token是干啥用的啊

### ISSUE THREAD

**Issue by liyanfei250** [YoungNK/TransferDemo#1]

**Comment by ShawnSol** [comment]
这个项目是本地录制视频之后上传的，上传是传到七牛的服务器，所以这个token是认证用的，这个东西做一半搁浅了，所以Android代码公开了，服务端代码就是生成一个token

**Comment by liyanfei250** [comment]
嗯！懂了，这个服务器是托管平台？是否收费，视频上传之后可以获取吧

在 2016-10-12 16:21:31，"Shawn Sol" <notifications@github.com> 写道：


这个项目是本地录制视频之后上传的，上传是传到七牛的服务器，所以这个token是认证用的，这个东西做一半搁浅了，所以Android代码公开了，服务端代码就是生成一个token

**Comment by ShawnSol** [comment]
你可以去七牛看看，小规模使用免费的，商用量大要收费。
上面有详细的文档
